-- Create the expenses table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  title TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  category TEXT NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- Create policies to allow users to manage only their own data

-- Policy for SELECT
CREATE POLICY "Users can view their own expenses" ON expenses
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy for INSERT
CREATE POLICY "Users can insert their own expenses" ON expenses
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy for UPDATE
CREATE POLICY "Users can update their own expenses" ON expenses
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Policy for DELETE
CREATE POLICY "Users can delete their own expenses" ON expenses
  FOR DELETE
  USING (auth.uid() = user_id);
